
name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x64]
        include:
          - os: macos-latest
            architecture: arm64
          - os: ubuntu-latest
            architecture: arm64
          - os: ubuntu-latest
            architecture: armv7l
          - os: ubuntu-latest
            architecture: ppc64le
          - os: ubuntu-latest
            architecture: s390x
          - os: windows-latest
            architecture: x86

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^7.26.2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          architecture: ${{ matrix.architecture }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
